### ISSUE TITLE
[Enhancement]World gen ores need some attention

### ISSUE THREAD

**Issue by Electrofried** [CaiganMythFang/FOG_of_Magic#11]
Currently there are half a dozen versions of copper, tin and other ores spawning from multiple mods. This leads to overflowing backpacks, messy storage, and generally messy world gen. 
Perhaps it might be good to pick one mod that you enjoy the look of the ores from (I am partial to create myself as they have mechanics like copper corroding when touching air), disabling the rest and then tweaking the world gen levels of the mod(s) you choose to the level of ore generation you expect in your pack.  
Thanks for all your hard work!

**Comment by Gamebuster19901** [comment]
Although multiple versions of copper generate, when picked up, the item is always changed into `create:copper_ore`, so there is no negative effects for storage.

However it does make copper extremely common, even though there is a quest that states it's rarer than iron, I don't think that's the case.
