### ISSUE TITLE
Nature's Aura decayed leaves crash the server

### ISSUE THREAD

**Issue by Naroro766** [CaiganMythFang/FOG_of_Magic#14]
When draining aura doing the ritual of the forest, the nearby ancient tree leaves, when decayed, crash the server. Whenever the server is restarted and the chunk in question is loaded, the server crashes.
[latest.log](https://github.com/CaiganMythFang/FOG_of_Magic/files/6380819/latest.log)

**Comment by CaiganMythFang** [comment]
Okay I see what is causing the issue here 

To fix it for now, you can disable Rapid Leaf Decay mod until I put out the next update later this week.
