### ISSUE TITLE
Issue with Quests

### ISSUE THREAD

**Issue by Kristi1980** [CaiganMythFang/FOG_of_Magic#19]
I just started playing this modpack a few days ago and I have run into an issue with quests not registering items for completion. Specifically, the Inventory Pet quest, with the Pixie and the Feed Bag. The feed bag is not showing the recipe when you click on it, and I have made the feed bag and the pixie, both are in my inventory, and the quest is not completing. There is also no option to submit the items, so that quest won't complete, which keeps other quests locked.

**Comment by CaiganMythFang** [comment]
No other quests are connected to the Inventory Pet quest, so there shouldn't be a worry there.

I've fixed the issue for the next update though.
