### ISSUE TITLE
Collecting a silkworm egg grants the Captured advancement

### ISSUE THREAD

**Issue by Gamebuster19901** [CaiganMythFang/FOG_of_Magic#7]
Collecting a `mysticalworld:silkwork_egg` grants the `Captured` advancement from `Apotheosis Spawners`

Apotheosis Spawners sees the silkworm egg as a spawn egg.

**Comment by CaiganMythFang** [comment]
Hmm, it seems to see both the actual spawn egg and the normal egg as a spawn egg (technically not wrong?). There isn't much I can do about that I believe, but it doesn't really effect much beyond the achievement as far as I know.
